### ISSUE TITLE
RTS and IRQ pins

### ISSUE THREAD

**Issue by mike-rankin** [denisn73/AT42QT#3]
The example sketch mentions the RTS and IRQ pins but the AT42QT parts do not have these pins. On the datasheet I see a Change, RST, i2c pins and a few others but no RTS and IRQ.

**Comment by denisn73** [comment]
> 

Hi. Here is literal error — RTS is RST (Reset). See "begin" counstructor's agruments to use Reset pin.
IRQ — it is interrupt pin on MCU, but not pin name on the atmel chip. On the atmel chip it is pin CHANGE, for indicate status flag changes and the example provide handle this changes with interrupt
